# Generated by Django 5.2 on 2025-05-05 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_userprofile_profile_image_userprofile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testanswer',
            old_name='answer_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='testquestion',
            old_name='question_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='testresult',
            name='taken_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
